---
title: "HW 07 Part 1: Data Visualization"
author: "Andrew Chronister"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GGally)
library(patchwork)
```

#Setting the data filepath
```{r}
file_path <-"~/Documents/BI685Files/GitHubDocs/chronister_andrew/data"
sparrows_raw <- read_tsv(file.path(file_path, "sparrows.txt"))
View(sparrows_raw)
sparrows_raw
```
```{r}
sparrows <- sparrows_raw %>%
  mutate(box_group = "Sparrows",
         row_order = 1:nrow(.))
View(sparrows)
```
#Figure 2: Outliers 
```{r}
plot_box <- sparrows %>%
  ggplot(aes(x = box_group,
             y = wingcrd))+
  geom_boxplot(width = 0.25)+
  labs(x = NULL,
       y = "Wing length (mm)")
```
#Create Cleveland plot
```{r}
plot_cleveland <- sparrows %>%
  ggplot(aes(x = wingcrd,
             y = row_order))+
  geom_point()+
  labs(x = "Wing length (mm)",
       y = "Order of the data")
```
#Store plots into variables...
#Plot both plots side by side.
```{r}
plot_box + plot_cleveland
```
#Add Coordinate Flip so scales line up
```{r}
plot_box + plot_cleveland + coord_flip()
```



