---
title: "chronister_09.Rmd"
author: "Andrew Chronister"
output: html_notebook
---

***
### Chapter 14 examples
#Load the libraries
```{r}
library(tidyverse)
library(stringr)
library(htmlwidgets)
library(nycflights13)

```

```{r}
x <- c("\"", "\\")
x
writeLines(x)
```
```{r}
x <- c("\"They'll be back in time for lunch\\dinner\", is what she said.")
y <- c("The quick brown fox jumped over the lazy dog.")
writeLines(x)
writeLines(y)
str_c("x", "y")
str_view(x, "id\\.")
str_view(x, "\\\\din")

```
```{r}
str_c(c("x", "y", "z"), collapse = "")
```
```{r}
x <- c("a", "abc", "abcd", "abcde", "abcdef")
L <- str_length(x)
m <- ceiling(L/2)
str_sub(x, m, m)
```
```{r}
geez <- c("\"'\\")
str_view("\"'\\", "\"'\\\\", match = TRUE)

```

```{r}
length(sentences)
head(sentences)
```

```{r}
colors <- c("red", "orange", "yellow", "green", "blue", "purple")
color_match <- str_c("\\b(", str_c(colors, collapse = "|"), ")\\b")
color_match


```
```{r}
has_color <- str_subset(sentences, color_match)
matches <- str_extract(has_color, color_match)
head(matches)

```
```{r}
more <- sentences[str_count(sentences, color_match)>1]
str_view_all(more, color_match)
str_extract(more, color_match)
str_extract_all(more, color_match, simplify = TRUE)
```
```{r}
noun <- "(a|the) ([^ ]+)"
has_noun <- sentences %>%
  str_subset(noun)%>%
  head(10)
has_noun%>%
  str_extract(noun)
```
```{r}
has_noun%>%
  str_match(noun)
```
```{r}
tibble(sentence = sentences)%>%
  tidyr::extract(
    sentence, c("article", "noun"),  "(a|the) ([^ ]+)",
    remove = FALSE
  )
```

```{r}
numword <- "(one|two|three|four|five|six|seven|eight|nine|ten) +\\S+"
sentences[str_detect(sentences, numword)] %>%
  str_extract(numword)
```

```{r}
sentences%>%
  head(5)%>%
  str_split(" ")
```

```{r}
x <- "This is a sentence.  This is another sentence."
str_view_all(x, boundary("word"))
```

```{r}
dna <- "ATCACTAAATATGATTTGTGTAAAACCAAAATAAGATCTACAAACGAATAGAAGCTAGAGCGAAAAATGG"
str_count(dna, "[CGT]A{2,4}[CGT]")

```
```{r}
example(str_c)
```
```{r}
flights2 <- flights%>%
  select(year:day, hour, origin, dest, tailnum, carrier)
flights2
```

```{r}
flights2%>%
  select(-origin, -dest)%>%
  left_join(airlines, by = "carrier")
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     1, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2"
)
left_join(x,y, by = "key")
```

```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     3, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     2, "y3",
     3, "y4"
)
left_join(x, y, by="key")
```



