---
title: "HW10: Maps"
author: "Andrew Chronister"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
***
###Change knit directory
```{r}
knitr::opts_knit$set(root.dir = '~/Documents/BI685Files/GitHubDocs/chronister_andrew/')
```
***
###Install packages
***
###Load libraries
```{r}
library(raster)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(maptools)
library(ggmap)
library(marmap)
```
***
###Part 1: Outline maps
```{r}
usa <- map_data(map="state")
us_missouri <- map_data(map="state",
                        region="missouri")
us_other <- subset(x=usa,
                   subset=region %in% c("alabama",
                                        "florida",
                                        "mississippi",
                                        "north carolina"))
```

```{r}
str(usa)
```
```{r}
ggplot()+
  geom_polygon(data=us_other,
               aes(x=long,
                   y=lat,
                   group=group),
               fill = "gray")
```

```{r}
ggplot()+
  geom_polygon(data = us_other,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="gray")+
  geom_polygon(data=us_missouri,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="black")
```

```{r}
ggplot()+
  geom_polygon(data = us_other,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="gray")+
  geom_polygon(data=us_missouri,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="black")+
  geom_polygon(data = usa,
               aes(x=long,
                   y=lat,
                   group=group),
               fill=NA,
               color="black")
```

```{r}
us_map <- ggplot()+
  geom_polygon(data = us_other,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="gray")+
  geom_polygon(data=us_missouri,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="black")+
  geom_polygon(data=usa,
               aes(x=long,
                   y=lat,
                   group=group),
               fill=NA,
               color="black")+
  theme_map()+
  coord_fixed(1.3)
us_map
```
#Missouri map 
```{r}
missouri <- map_data("county", "missouri")
mo_scott <- subset(missouri, subregion %in% c("scott"))
mo_map <- ggplot()+
  geom_polygon(data=missouri, aes(x=long, y=lat, group=group), fill=NA, color="black")+
  geom_polygon(data=mo_scott, aes(x=long, y=lat, group=group), fill="black")+
  theme_map()+
  coord_fixed(1.3)
mo_map
```

```{r}
us_map + mo_map + plot_layout(ncol = 2, widths = c(1.5, 1))
```
#Outline Maps
#This should be interesting... I was born in Hawaii. It isn't part of the map_data, so I'll choose Utah, where I lived for two years and learned to ski.   
```{r}
us_utah <- map_data(map="state",
                      region = "utah")
utah <- map_data("county", "utah")
ut_birth <- subset(utah, subregion %in% c("weber"))
ut_names <- subset(utah, subregion %in% c("carbon", "kane"))

akc_usa <- ggplot()+
  geom_polygon(data = us_utah,
               aes(x = long,
               y = lat,
               group = group),
               fill = "black")+
  geom_polygon(data = usa,
               aes(x = long,
               y = lat,
               group = group),
               fill = NA,
               color = "black")+
  theme_map()+
  coord_fixed(1.3)

akc_counties <- ggplot()+
  geom_polygon(data = ut_birth,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "black")+
  geom_polygon(data = ut_names,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "gray")+
  geom_polygon(data = utah,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = NA,
               color = "black")+
  theme_map()+
  coord_fixed(1.3)

akc_usa + akc_counties + plot_layout(ncol = 2, widths = c(1.5,1))
```



