---
title: "HW 06 Part 2: Wrangling II"
author: "Andrew Chronister"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

#Load tidyverse and knitr libraries
```{r}
library(tidyverse)
library(knitr)
install.packages("smatr")
library(smatr)
```
#defining path variable
```{r}
file_path <- "~/Documents/BI685Files/GitHubDocs/chronister_andrew/data/"
```
#Read in darters.txt
```{r}
start_pos <-  c(1,4,15,16,17,18,21,25,29,33,36,39,41)
stop_pos <- c(3,14,15,16,17,20,24,28,32,35,38,40,42)
names <- c("specimen id", "species", "riffle", "age", "sex", "length", "depth", "velocity", "temperature", "majsub", "minsub", "majtype", "mintype")
darters <- read_fwf(file.path(file_path, "darter.txt"), fwf_positions(start_pos, stop_pos, col_names = names), skip = 13)
darters
```
#remove tetrazonum and zonale
```{r}
darters2 <- darters %>%
  filter(!species %in% c("tetrazonum", "zonale"))
darters2
```
#Wrangle data
```{r}
  mutate(darters2,
       total_substrate = majsub + minsub
       )
```
#My calculations show that total_substrate = 1 for all observations.  

```{r}
mutate(darters2,
       total_substrate = majsub + minsub
       )

```
#Change riffle values
```{r}
  mutate(darters2,
         riffle = ifelse(riffle == 1,
                         "Riffle 1",
                         "Riffle 2"))
```
#Change length data from cm to mm
```{r}
  mutate(darters2,
         length = length * 10)
```
#Change sex values
```{r}
  mutate(darters2,
         sex = ifelse(sex == "f",
                      "Female",
                      "Male"))
```
#Summarize data
```{r}
darters_species_means <- darters2 %>%
  group_by(species, riffle) %>%
  summarize(length = mean(length, na.rm = TRUE),
            depth = mean(depth, na.rm = TRUE),
            velocity = mean(velocity, na.rm = TRUE)
            )
darters_species_means
```
#Plot 1
```{r}
ggplot(data = darters_species_means) +
  stat_summary(mapping = aes(x=species, y=length),
               fun.ymin = min,
               fun.ymax = max,
               fun.y = median
               ) +
  geom_point(data = darters_species_means, mapping = aes(x=species, y=length), shape = 15)
  
```
#Turn plot, add facetwrap and labs
```{r}
ggplot(data = darters_species_means) +
  stat_summary(mapping = aes(x=species, y=length),
               fun.ymin = min,
               fun.ymax = max,
               fun.y = median
               ) +
  geom_point(data = darters_species_means, mapping = aes(x=species, y=length), shape = 15)+
  coord_flip() +
  facet_wrap(~riffle, nrow = 2)+
  labs(x=NULL, y="Length (cm)")
```


